### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by klzns** [vtex/i18n#4]
- [x] Perguntas frequentes vai pra versão em pt https://vtex.slack.com/archives/C4L2ARDU3/p1518716392000671?thread_ts=1518712733.001094&cid=C4L2ARDU3
- [x] Contactos https://vtex.slack.com/archives/C4L2ARDU3/p1518716341000700?thread_ts=1518712733.001094&cid=C4L2ARDU3
- [x] Endereço https://vtex.slack.com/archives/C4L2ARDU3/p1518716237000535?thread_ts=1518712733.001094&cid=C4L2ARDU3
- [x] Contactos 2 https://vtex.slack.com/archives/C4L2ARDU3/p1518716050000248?thread_ts=1518712733.001094&cid=C4L2ARDU3

**Comment by kevinch** [comment]
https://github.com/vtex/billing-ui/pull/266

**Comment by kevinch** [comment]
Pontos 2, 3 & 4: https://github.com/vtex/billing-ui/pull/268
