### ISSUE TITLE
License Manager

### ISSUE THREAD

**Issue by klzns** [vtex/i18n#7]
Todo o modulo
https://vtex.slack.com/archives/C4L2ARDU3/p1518715231000568?thread_ts=1518712733.001094&cid=C4L2ARDU3
https://vtex.slack.com/archives/C4L2ARDU3/p1518715288000658?thread_ts=1518712733.001094&cid=C4L2ARDU3

**Comment by Abinader** [comment]
@klzns , essas páginas já estão traduzidas.

![image](https://user-images.githubusercontent.com/1301081/36487506-d9d79356-16ff-11e8-8ed1-d3963c05841d.png)
![image](https://user-images.githubusercontent.com/1301081/36487517-e0fd38ac-16ff-11e8-8d9c-3d1845fcd496.png)

**Comment by klzns** [comment]
![screen shot 2018-02-21 at 4 05 05 pm](https://user-images.githubusercontent.com/284515/36552398-8606f3f0-17d8-11e8-8f23-710f247596bf.png)

> gente, fui entrar no license manager aqui e tem uma serie de coisas em portugues / erradas - editar conta, ativo, sim, saver, moeda, as opções de moeda, CNPJ, responsible name / responsible email (nao faz sentido)

https://vtex.slack.com/archives/C4L2ARDU3/p1519240414000264

**Comment by rnbez** [comment]
em beta
